# Generated by Django 5.1.1 on 2024-09-27 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.region')),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fish', models.CharField(max_length=255)),
                ('post_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.region')),
            ],
        ),
    ]
